export const workspaceMigrationEnglish: Record<string, string> = {
  '工作区数据位置': 'Workspace data location',
  '默认创建的笔记库、资料库及会话记忆保存在这里。更改位置时，会迁移现有工作区数据。': 'Default note libraries, material libraries, conversations and memories are stored here. Changing the location migrates the existing workspace data.',
  '更改存储位置…': 'Change storage location…',
  '打开其他工作区…': 'Open another workspace…',
  '打开文件夹': 'Open folder',
  '更改数据存储位置': 'Change data storage location',
  '选择新的数据存储位置：请选择空文件夹': 'Choose the new data location: select an empty folder',
  '打开已有工作区': 'Open an existing workspace',
  '继续上次迁移': 'Resume migration',
  '当前位置': 'Current location',
  '新位置': 'New location',
  '将迁移笔记、资料、附件、备份、会话、记忆和技能文件。': 'Notes, materials, attachments, backups, conversations, memories and skill files will be migrated.',
  '{count} 个文件': '{count} files',
  '以下外部库保留原位置，继续关联：': 'These external libraries stay in their current locations and remain connected: ',
  '完成后自动启用新位置。原目录保留为迁移前副本，模型配置和密钥继续沿用。': 'The new location is enabled automatically. The original folder is kept as a pre-migration copy. Model settings and credentials remain available.',
  '正在加载新位置的数据。': 'Loading data from the new location.',
  '正在读取工作区信息。': 'Reading workspace information.',
  '数据迁移进度': 'Data migration progress',
  '{completed} / {total} 个文件': '{completed} / {total} files',
  '保存当前内容': 'Save current changes',
  '迁移文件': 'Copy files',
  '关联历史与记忆': 'Reconnect history and memories',
  '校验数据': 'Validate data',
  '启用新位置': 'Enable new location',
  '取消迁移': 'Cancel migration',
  '打开新位置': 'Open new location',
  '重试加载': 'Retry loading',
  '继续使用原位置': 'Use original location',
  '开始迁移': 'Start migration',
  '继续迁移': 'Resume migration',
  '上次迁移未完成，可以继续迁移或使用原位置。': 'The previous migration was interrupted. Resume it or use the original location.',
  '正在保存当前内容并等待后台任务结束。': 'Saving current changes and waiting for background tasks.',
  '正在迁移文件和数据库。': 'Copying files and databases.',
  '正在关联笔记、会话和记忆。': 'Reconnecting notes, conversations and memories.',
  '正在校验迁移结果。': 'Validating migrated data.',
  '正在启用新位置，完成后即可继续使用。': 'Enabling the new location. You can continue once this finishes.',
  '正在恢复新位置的数据关联。': 'Restoring connections at the new location.',
  '迁移完成，已启用新位置。原目录保留为迁移前副本。': 'Migration completed. The new location is active, and the original folder is kept as a pre-migration copy.',
  '已继续使用原位置，原数据未改变。': 'The original location is active. The original data is unchanged.',
  '迁移已取消，原位置的数据仍然保留。': 'Migration cancelled. Data remains at the original location.',
  '目录被其他程序占用或没有写入权限。请关闭占用程序后重试，或继续使用原位置。': 'The folder is in use or is not writable. Close the program using it and retry, or use the original location.',
  '磁盘空间不足，原数据仍在原位置，请清理空间后重试。': 'There is not enough disk space. Data remains at the original location. Free up space and retry.',
  '目标文件夹必须为空，迁移不会覆盖已有文件。': 'The destination must be empty. Migration does not overwrite existing files.',
  '新位置的数据暂未加载，请重试加载。': 'Data at the new location has not loaded yet. Retry loading.',
};
